spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
    url: jdbc:h2:tcp://localhost/~/test
    driverClassName: org.h2.Driver
    username: sa
    password:


mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: null



